# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios ,'10.0'

target 'HZTT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'SVProgressHUD'
	pod 'MBProgressHUD'
	#pod 'LKDBHelper', '~> 2.4.2'
	pod 'RxSwift'
	pod 'RxCocoa'
	#pod 'RxDataSources', '~> 1.0.4'
	pod 'SnapKit'
	pod 'Moya/RxSwift'


	pod 'MJRefresh','3.1.12'
	pod 'Kingfisher', '~> 5.10'
	pod 'IQKeyboardManagerSwift', '~> 6.0.0'
	pod 'JXSegmentedView'
	
	# 导航栏
	pod 'HBDNavigationBar'
	
	#图片选择器
	pod 'TZImagePickerController'
	pod 'SKPhotoBrowser'
	
	#版本兼容问题
	#pod 'LinkLabel'
	
	

  # Pods for HZTT

end
